# coding: utf-8

"""
    The ParaBank REST API

    This API provides access to various ParaBank internal operations  # noqa: E501

    OpenAPI spec version: 3.0.0
    Contact: webadmin@parabank.parasoft.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.loans_api import LoansApi  # noqa: E501
from swagger_client.rest import ApiException


class TestLoansApi(unittest.TestCase):
    """LoansApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.loans_api.LoansApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_request_loan1(self):
        """Test case for request_loan1

        Request a loan  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
