# coding: utf-8

"""
    The ParaBank REST API

    This API provides access to various ParaBank internal operations  # noqa: E501

    OpenAPI spec version: 3.0.0
    Contact: webadmin@parabank.parasoft.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.accounts_api import AccountsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAccountsApi(unittest.TestCase):
    """AccountsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.accounts_api.AccountsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_bill_pay1(self):
        """Test case for bill_pay1

        Pay bill  # noqa: E501
        """
        pass

    def test_create_account1(self):
        """Test case for create_account1

        Create a new account  # noqa: E501
        """
        pass

    def test_deposit1(self):
        """Test case for deposit1

        Deposit funds  # noqa: E501
        """
        pass

    def test_get_account1(self):
        """Test case for get_account1

        Get Account by Id  # noqa: E501
        """
        pass

    def test_get_accounts1(self):
        """Test case for get_accounts1

        Get Customer Accounts  # noqa: E501
        """
        pass

    def test_get_transactions1(self):
        """Test case for get_transactions1

        Get the list of Transactions for the account  # noqa: E501
        """
        pass

    def test_get_transactions_by_amount1(self):
        """Test case for get_transactions_by_amount1

        Create transactions by amount for account  # noqa: E501
        """
        pass

    def test_get_transactions_by_month_and_type1(self):
        """Test case for get_transactions_by_month_and_type1

        Fetch transactions by month and type for account  # noqa: E501
        """
        pass

    def test_get_transactions_by_to_from_date1(self):
        """Test case for get_transactions_by_to_from_date1

        Fetch transactions for date range for account  # noqa: E501
        """
        pass

    def test_get_transactions_on_date1(self):
        """Test case for get_transactions_on_date1

        Fetch transactions for a specific date for account  # noqa: E501
        """
        pass

    def test_transfer1(self):
        """Test case for transfer1

        Transfer funds  # noqa: E501
        """
        pass

    def test_withdraw1(self):
        """Test case for withdraw1

        Withdraw funds  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
