# coding: utf-8

"""
    The ParaBank REST API

    This API provides access to various ParaBank internal operations  # noqa: E501

    OpenAPI spec version: 3.0.0
    Contact: webadmin@parabank.parasoft.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.history_point import HistoryPoint  # noqa: E501
from swagger_client.rest import ApiException


class TestHistoryPoint(unittest.TestCase):
    """HistoryPoint unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHistoryPoint(self):
        """Test HistoryPoint"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.history_point.HistoryPoint()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
