# coding: utf-8

"""
    The ParaBank REST API

    This API provides access to various ParaBank internal operations  # noqa: E501

    OpenAPI spec version: 3.0.0
    Contact: webadmin@parabank.parasoft.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.transactions_api import TransactionsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTransactionsApi(unittest.TestCase):
    """TransactionsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.transactions_api.TransactionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_transaction1(self):
        """Test case for get_transaction1

        Get the transaction for the id  # noqa: E501
        """
        pass

    def test_get_transactions1(self):
        """Test case for get_transactions1

        Get the list of Transactions for the account  # noqa: E501
        """
        pass

    def test_get_transactions_by_amount1(self):
        """Test case for get_transactions_by_amount1

        Create transactions by amount for account  # noqa: E501
        """
        pass

    def test_get_transactions_by_month_and_type1(self):
        """Test case for get_transactions_by_month_and_type1

        Fetch transactions by month and type for account  # noqa: E501
        """
        pass

    def test_get_transactions_by_to_from_date1(self):
        """Test case for get_transactions_by_to_from_date1

        Fetch transactions for date range for account  # noqa: E501
        """
        pass

    def test_get_transactions_on_date1(self):
        """Test case for get_transactions_on_date1

        Fetch transactions for a specific date for account  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
