# coding: utf-8

"""
    The ParaBank REST API

    This API provides access to various ParaBank internal operations  # noqa: E501

    OpenAPI spec version: 3.0.0
    Contact: webadmin@parabank.parasoft.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.positions_api import PositionsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPositionsApi(unittest.TestCase):
    """PositionsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.positions_api.PositionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_buy_position1(self):
        """Test case for buy_position1

        Buy a Position  # noqa: E501
        """
        pass

    def test_get_position1(self):
        """Test case for get_position1

        Get Position by id  # noqa: E501
        """
        pass

    def test_get_position_history1(self):
        """Test case for get_position_history1

        Get Position history by id within a date range  # noqa: E501
        """
        pass

    def test_get_positions1(self):
        """Test case for get_positions1

        Get Positions for Customer  # noqa: E501
        """
        pass

    def test_sell_position1(self):
        """Test case for sell_position1

        Sell a Position  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
