# coding: utf-8

"""
    The ParaBank REST API

    This API provides access to various ParaBank internal operations  # noqa: E501

    OpenAPI spec version: 3.0.0
    Contact: webadmin@parabank.parasoft.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.misc_api import MiscApi  # noqa: E501
from swagger_client.rest import ApiException


class TestMiscApi(unittest.TestCase):
    """MiscApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.misc_api.MiscApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_login1(self):
        """Test case for login1

        Login (john/demo)  # noqa: E501
        """
        pass

    def test_set_parameter1(self):
        """Test case for set_parameter1

        Set Parameters  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
