# coding: utf-8

"""
    The ParaBank REST API

    This API provides access to various ParaBank internal operations  # noqa: E501

    OpenAPI spec version: 3.0.0
    Contact: webadmin@parabank.parasoft.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.customers_api import CustomersApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCustomersApi(unittest.TestCase):
    """CustomersApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.customers_api.CustomersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_account1(self):
        """Test case for create_account1

        Create a new account  # noqa: E501
        """
        pass

    def test_get_accounts1(self):
        """Test case for get_accounts1

        Get Customer Accounts  # noqa: E501
        """
        pass

    def test_get_customer1(self):
        """Test case for get_customer1

        Get Customer Details  # noqa: E501
        """
        pass

    def test_get_positions1(self):
        """Test case for get_positions1

        Get Positions for Customer  # noqa: E501
        """
        pass

    def test_update_customer1(self):
        """Test case for update_customer1

        Update customer information  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
